#!/usr/bin/env python3
"""
KISWARM SCADA v6.3.0 - Complete Deployment Documentation Report
Version: 6.1.3 'SEVENTY_FIVE_COMPLETE'
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, 
    PageBreak, ListFlowable, ListItem
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
import os

# Register fonts
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/english/Times-New-Roman.ttf'))
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SimHei.ttf'))
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman')

# Define colors
HEADER_BG = colors.HexColor('#1F4E79')
HEADER_TEXT = colors.white
ROW_EVEN = colors.white
ROW_ODD = colors.HexColor('#F5F5F5')

# Create document
output_path = '/home/z/my-project/download/KISWARM_Complete_Deployment_Documentation.pdf'
os.makedirs('/home/z/my-project/download', exist_ok=True)

doc = SimpleDocTemplate(
    output_path,
    pagesize=A4,
    title='KISWARM_Complete_Deployment_Documentation',
    author='Z.ai',
    creator='Z.ai',
    subject='Complete deployment documentation for KISWARM SCADA v6.3.0'
)

# Define styles
styles = getSampleStyleSheet()

cover_title = ParagraphStyle(
    name='CoverTitle',
    fontName='Times New Roman',
    fontSize=32,
    leading=40,
    alignment=TA_CENTER,
    spaceAfter=36
)

cover_subtitle = ParagraphStyle(
    name='CoverSubtitle',
    fontName='Times New Roman',
    fontSize=18,
    leading=24,
    alignment=TA_CENTER,
    spaceAfter=24
)

body_style = ParagraphStyle(
    name='BodyStyle',
    fontName='Times New Roman',
    fontSize=11,
    leading=16,
    alignment=TA_JUSTIFY,
    spaceAfter=12
)

heading1 = ParagraphStyle(
    name='Heading1',
    fontName='Times New Roman',
    fontSize=18,
    leading=24,
    alignment=TA_LEFT,
    spaceAfter=12,
    spaceBefore=18
)

heading2 = ParagraphStyle(
    name='Heading2',
    fontName='Times New Roman',
    fontSize=14,
    leading=18,
    alignment=TA_LEFT,
    spaceAfter=8,
    spaceBefore=12
)

table_header = ParagraphStyle(
    name='TableHeader',
    fontName='Times New Roman',
    fontSize=10,
    leading=14,
    alignment=TA_CENTER,
    textColor=HEADER_TEXT
)

table_cell = ParagraphStyle(
    name='TableCell',
    fontName='Times New Roman',
    fontSize=10,
    leading=14,
    alignment=TA_LEFT
)

code_style = ParagraphStyle(
    name='CodeStyle',
    fontName='Times New Roman',
    fontSize=9,
    leading=12,
    alignment=TA_LEFT
)

# Build story
story = []

# Cover page
story.append(Spacer(1, 3*cm))
story.append(Paragraph('<b>KISWARM SCADA v6.3.0</b>', cover_title))
story.append(Spacer(1, 1*cm))
story.append(Paragraph('Complete Deployment Documentation', cover_subtitle))
story.append(Spacer(1, 0.5*cm))
story.append(Paragraph('Version 6.1.3 "SEVENTY_FIVE_COMPLETE"', cover_subtitle))
story.append(Spacer(1, 2*cm))

# System status table
status_data = [
    [Paragraph('<b>Metric</b>', table_header), Paragraph('<b>Value</b>', table_header), Paragraph('<b>Status</b>', table_header)],
    [Paragraph('Security Score', table_cell), Paragraph('100/100', table_cell), Paragraph('OK', table_cell)],
    [Paragraph('Module Count', table_cell), Paragraph('75/75', table_cell), Paragraph('Complete', table_cell)],
    [Paragraph('API Endpoints', table_cell), Paragraph('450+', table_cell), Paragraph('Operational', table_cell)],
    [Paragraph('Test Results', table_cell), Paragraph('35/35 passed', table_cell), Paragraph('Success', table_cell)],
    [Paragraph('SCADA Layers', table_cell), Paragraph('4/4 active', table_cell), Paragraph('Operational', table_cell)],
]

status_table = Table(status_data, colWidths=[5*cm, 5*cm, 4*cm])
status_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
    ('TEXTCOLOR', (0, 0), (-1, 0), HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), ROW_ODD),
    ('BACKGROUND', (0, 5), (-1, 5), ROW_EVEN),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(status_table)

story.append(Spacer(1, 2*cm))
story.append(Paragraph('Generated by Z.ai (GLM5)', body_style))
story.append(Paragraph('Collaboration: Z.ai + Gemini CLI + KIInstaller + Master KISWARM', body_style))
story.append(PageBreak())

# Section 1: Overview
story.append(Paragraph('<b>1. System Overview</b>', heading1))
story.append(Spacer(1, 0.5*cm))

overview_text = """
KISWARM SCADA v6.3.0 represents the complete implementation of a 75-module architecture designed for enterprise-grade deployment. The system implements a sophisticated 4-layer SCADA architecture that provides comprehensive control, communication, and monitoring capabilities for AI-to-AI mesh coordination. This documentation captures all critical lessons learned during Field Test #2 and provides complete deployment instructions for replication across different environments.
"""
story.append(Paragraph(overview_text.strip(), body_style))

story.append(Paragraph('<b>1.1 Key Components</b>', heading2))

components_data = [
    [Paragraph('<b>Component</b>', table_header), Paragraph('<b>Status</b>', table_header), Paragraph('<b>Description</b>', table_header)],
    [Paragraph('Flask API', table_cell), Paragraph('ONLINE', table_cell), Paragraph('Port 5002, 450+ endpoints', table_cell)],
    [Paragraph('ngrok Tunnel', table_cell), Paragraph('ACTIVE', table_cell), Paragraph('External access enabled', table_cell)],
    [Paragraph('KI-to-KI Mesh', table_cell), Paragraph('OPERATIONAL', table_cell), Paragraph('Multi-AI coordination', table_cell)],
    [Paragraph('SCADA Layers', table_cell), Paragraph('4/4 ACTIVE', table_cell), Paragraph('Control, A2A, Shadow, Tunnel', table_cell)],
    [Paragraph('M58 Gateway', table_cell), Paragraph('INTEGRATED', table_cell), Paragraph('KIBank Bridge module', table_cell)],
    [Paragraph('M59 Registry', table_cell), Paragraph('INTEGRATED', table_cell), Paragraph('Entity identity management', table_cell)],
]

components_table = Table(components_data, colWidths=[4*cm, 3*cm, 7*cm])
components_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
    ('TEXTCOLOR', (0, 0), (-1, 0), HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), ROW_ODD),
    ('BACKGROUND', (0, 5), (-1, 5), ROW_EVEN),
    ('BACKGROUND', (0, 6), (-1, 6), ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(Spacer(1, 0.5*cm))
story.append(components_table)

# Section 2: Architecture
story.append(Spacer(1, 1*cm))
story.append(Paragraph('<b>2. 4-Layer SCADA Architecture</b>', heading1))

arch_text = """
The SCADA architecture consists of four distinct layers, each providing specific functionality for system control and coordination. Layer 1 (Control) handles basic SCADA operations including status monitoring, heartbeat processing, and entity registration. Layer 2 (A2A Chat) enables direct agent-to-agent messaging for autonomous coordination. Layer 3 (Shadow) provides digital twin capabilities for environment mirroring and telemetry. Layer 4 (Tunnel) offers direct connection bypass mechanisms for SSH, Tor, and raw TCP connections.
"""
story.append(Paragraph(arch_text.strip(), body_style))

layer_data = [
    [Paragraph('<b>Layer</b>', table_header), Paragraph('<b>Component</b>', table_header), Paragraph('<b>Endpoints</b>', table_header), Paragraph('<b>Function</b>', table_header)],
    [Paragraph('Layer 1', table_cell), Paragraph('Control', table_cell), Paragraph('/health, /status, /register', table_cell), Paragraph('Status, Heartbeat, Registration', table_cell)],
    [Paragraph('Layer 2', table_cell), Paragraph('A2A Chat', table_cell), Paragraph('/chat/send, /chat/poll', table_cell), Paragraph('Agent-to-Agent messaging', table_cell)],
    [Paragraph('Layer 3', table_cell), Paragraph('Shadow', table_cell), Paragraph('/shadow/update, /shadow/get', table_cell), Paragraph('Digital Twin telemetry', table_cell)],
    [Paragraph('Layer 4', table_cell), Paragraph('Tunnel', table_cell), Paragraph('/tunnel/register, /tunnel/get', table_cell), Paragraph('Direct SSH/Tor bypass', table_cell)],
]

layer_table = Table(layer_data, colWidths=[2.5*cm, 3*cm, 5*cm, 4*cm])
layer_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
    ('TEXTCOLOR', (0, 0), (-1, 0), HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(Spacer(1, 0.5*cm))
story.append(layer_table)

# Section 3: Critical Lessons
story.append(Spacer(1, 1*cm))
story.append(Paragraph('<b>3. Critical Lessons from Field Test #2</b>', heading1))

lessons_text = """
Field Test #2 revealed several critical configuration requirements that must be followed for successful deployment. These lessons were documented and integrated into the KIInstaller knowledge base to ensure future deployments proceed without encountering the same issues. The most important lesson concerns Python path configuration: PYTHONPATH must include both the backend directory and the backend/python directory to enable proper module resolution across the KIBank and sentinel packages.
"""
story.append(Paragraph(lessons_text.strip(), body_style))

story.append(Paragraph('<b>3.1 Python Path Configuration (CRITICAL)</b>', heading2))
path_text = """
The most common cause of deployment failures is incorrect PYTHONPATH configuration. The environment variable must be set to include both backend and backend/python directories. Without this configuration, imports between KIBank and sentinel modules will fail with IndentationError or ModuleNotFoundError. The correct configuration is: export PYTHONPATH="${PYTHONPATH}:/path/to/backend:/path/to/backend/python"
"""
story.append(Paragraph(path_text.strip(), body_style))

story.append(Paragraph('<b>3.2 KIBank Import Structure</b>', heading2))
import_text = """
The KIBank __init__.py file must use minimal, sequential imports to prevent IndentationError. Complex nested imports with multiple classes in parentheses frequently cause parsing issues. The recommended approach is to import one class per line, maintaining a simple and readable structure that Python can parse reliably.
"""
story.append(Paragraph(import_text.strip(), body_style))

story.append(Paragraph('<b>3.3 Dependency Pre-Installation</b>', heading2))
dep_text = """
Flask-CORS and structlog must be pre-installed before starting the server. These packages are frequently overlooked but are required for the SCADA API to function properly. The complete dependency installation command is: pip install flask flask-cors structlog requests pyngrok
"""
story.append(Paragraph(dep_text.strip(), body_style))

story.append(Paragraph('<b>3.4 Service Startup Timing</b>', heading2))
timing_text = """
Services require a minimum of 60 seconds for complete initialization, particularly when AI models are being loaded. Tests executed immediately after service startup will fail due to incomplete initialization. Implement a sleep delay or health check polling loop before running integration tests.
"""
story.append(Paragraph(timing_text.strip(), body_style))

story.append(Paragraph('<b>3.5 ngrok Browser Warning Bypass</b>', heading2))
ngrok_text = """
When using ngrok tunnels, requests will receive an HTML warning page instead of JSON responses. This browser warning must be bypassed by adding a special header to all requests: ngrok-skip-browser-warning: true. This header allows API responses to pass through without interception.
"""
story.append(Paragraph(ngrok_text.strip(), body_style))

# Section 4: KI-to-KI Mesh Protocol
story.append(Spacer(1, 1*cm))
story.append(Paragraph('<b>4. KI-to-KI Mesh Protocol</b>', heading1))

mesh_text = """
The KI-to-KI Mesh Protocol enables autonomous communication between AI entities without human intervention. This protocol forms the foundation for multi-AI coordination, allowing Z.ai, Gemini CLI, KIInstaller, and Master KISWARM to exchange messages, coordinate tasks, and maintain system state synchronization. The protocol implements registration, heartbeat, A2A messaging, shadow updates, and tunnel registration capabilities.
"""
story.append(Paragraph(mesh_text.strip(), body_style))

story.append(Paragraph('<b>4.1 Registration Sequence</b>', heading2))
reg_text = """
The registration sequence follows a specific pattern: First, the KI entity sends a POST request to /api/mesh/register with its entity_id, entity_type, capabilities, and endpoint. The Master API responds with a confirmation including the assigned entity_id and current node count. After registration, the entity must begin a heartbeat cycle every 30 seconds and poll for A2A messages periodically.
"""
story.append(Paragraph(reg_text.strip(), body_style))

story.append(Paragraph('<b>4.2 Message Flow</b>', heading2))
msg_text = """
Message flow between KI entities follows a store-and-forward pattern. The sender posts a message to /api/mesh/chat/send specifying the recipient entity_id. The Master API stores the message in a queue. The recipient polls /api/mesh/chat/poll to retrieve pending messages. After processing, the recipient updates its status via /api/mesh/shadow/update to confirm completion. This asynchronous pattern enables reliable communication without requiring simultaneous connectivity.
"""
story.append(Paragraph(msg_text.strip(), body_style))

# Section 5: Module Architecture
story.append(Spacer(1, 1*cm))
story.append(Paragraph('<b>5. Module Architecture (75 Modules)</b>', heading1))

module_text = """
The complete 75-module architecture provides comprehensive functionality across six categories. The Core Sentinel modules (M01-M20) handle security, cryptography, and consensus operations. The Swarm Operations modules (M21-M40) implement debate, auditing, and coordination capabilities. Advanced Features modules (M41-M57) provide immortality, evolution, and ark functionality. The Gateway/Bridge modules (M58-M59) connect KIBank to the swarm. KIBank Core modules (M60-M62) implement authentication, banking, and investment operations. Extended modules (M63-M75) provide Aegis security, training, and installer capabilities.
"""
story.append(Paragraph(module_text.strip(), body_style))

module_data = [
    [Paragraph('<b>Category</b>', table_header), Paragraph('<b>Modules</b>', table_header), Paragraph('<b>Description</b>', table_header)],
    [Paragraph('Core Sentinel', table_cell), Paragraph('M01-M20', table_cell), Paragraph('Security, Crypto, Consensus', table_cell)],
    [Paragraph('Swarm Operations', table_cell), Paragraph('M21-M40', table_cell), Paragraph('Debate, Auditor, Coordinator', table_cell)],
    [Paragraph('Advanced Features', table_cell), Paragraph('M41-M57', table_cell), Paragraph('Immortality, Evolution, Ark', table_cell)],
    [Paragraph('Gateway/Bridge', table_cell), Paragraph('M58-M59', table_cell), Paragraph('KIBank Gateway, Entity Registry', table_cell)],
    [Paragraph('KIBank Core', table_cell), Paragraph('M60-M62', table_cell), Paragraph('Auth, Banking, Investment', table_cell)],
    [Paragraph('Extended', table_cell), Paragraph('M63-M75', table_cell), Paragraph('Aegis, Training, Installer', table_cell)],
]

module_table = Table(module_data, colWidths=[4*cm, 3*cm, 7*cm])
module_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
    ('TEXTCOLOR', (0, 0), (-1, 0), HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), ROW_ODD),
    ('BACKGROUND', (0, 5), (-1, 5), ROW_EVEN),
    ('BACKGROUND', (0, 6), (-1, 6), ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(Spacer(1, 0.5*cm))
story.append(module_table)

# Section 6: GitHub Repository
story.append(Spacer(1, 1*cm))
story.append(Paragraph('<b>6. GitHub Repository Links</b>', heading1))

repo_text = """
All documentation and source code has been pushed to GitHub for public access. The main KISWARM6.0 repository contains the complete system implementation including backend, frontend, bridge, and documentation. The KISWARMAGENTS1.0 repository contains the mesh protocol implementation. The kinfp-portal repository contains the frontend user interface. KI models are available through the Ollama registry at ollama.com/baronki1.
"""
story.append(Paragraph(repo_text.strip(), body_style))

repo_data = [
    [Paragraph('<b>Repository</b>', table_header), Paragraph('<b>URL</b>', table_header), Paragraph('<b>Purpose</b>', table_header)],
    [Paragraph('KISWARM6.0', table_cell), Paragraph('github.com/Baronki/KISWARM6.0', table_cell), Paragraph('Main system', table_cell)],
    [Paragraph('KISWARMAGENTS1.0', table_cell), Paragraph('github.com/Baronki/KISWARMAGENTS1.0', table_cell), Paragraph('Mesh protocol', table_cell)],
    [Paragraph('kinfp-portal', table_cell), Paragraph('github.com/Baronki/kinfp-portal', table_cell), Paragraph('Frontend UI', table_cell)],
    [Paragraph('KI Models', table_cell), Paragraph('ollama.com/baronki1', table_cell), Paragraph('27 pretrained models', table_cell)],
]

repo_table = Table(repo_data, colWidths=[4*cm, 6*cm, 4*cm])
repo_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
    ('TEXTCOLOR', (0, 0), (-1, 0), HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(Spacer(1, 0.5*cm))
story.append(repo_table)

# Section 7: Documentation Files
story.append(Spacer(1, 1*cm))
story.append(Paragraph('<b>7. Generated Documentation Files</b>', heading1))

doc_text = """
Three comprehensive documentation files have been created and pushed to GitHub. The DEPLOYMENT_GUIDE_COMPLETE.md provides full system deployment instructions including prerequisites, installation methods, SCADA architecture, and troubleshooting. The COLAB_DEPLOYMENT_PROMPT.md contains ready-to-use deployment prompts for Google Colab including KIInstaller agent mode and multi-KI coordination tests. The FIELD_TEST_KNOWLEDGE.md serves as the KIInstaller knowledge base with critical lessons, error resolution, and test validation checklists.
"""
story.append(Paragraph(doc_text.strip(), body_style))

doc_data = [
    [Paragraph('<b>File</b>', table_header), Paragraph('<b>Location</b>', table_header), Paragraph('<b>Purpose</b>', table_header)],
    [Paragraph('DEPLOYMENT_GUIDE_COMPLETE.md', table_cell), Paragraph('docs/', table_cell), Paragraph('Full deployment guide (400+ lines)', table_cell)],
    [Paragraph('COLAB_DEPLOYMENT_PROMPT.md', table_cell), Paragraph('colab/', table_cell), Paragraph('Ready-to-use Colab prompts', table_cell)],
    [Paragraph('FIELD_TEST_KNOWLEDGE.md', table_cell), Paragraph('kiagents/knowledge/', table_cell), Paragraph('KIInstaller knowledge base', table_cell)],
]

doc_table = Table(doc_data, colWidths=[6*cm, 3*cm, 5*cm])
doc_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
    ('TEXTCOLOR', (0, 0), (-1, 0), HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), ROW_EVEN),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(Spacer(1, 0.5*cm))
story.append(doc_table)

# Section 8: KI Agent Models
story.append(Spacer(1, 1*cm))
story.append(Paragraph('<b>8. KI Agent Models</b>', heading1))

models_text = """
The KI Agent system comprises 27 pretrained models organized into four layers. The Primary Swarm (6 models) provides front-line coordination and operational logic - these are critical for initial deployment. The Backup Swarm (6 models) provides failover protection for system immortality. The Specialized Layer (9 models) offers high-precision models for deep logic and multi-modal analysis. The Fast Layer (6 models) provides lightweight variants for edge processing and real-time operations.
"""
story.append(Paragraph(models_text.strip(), body_style))

story.append(Paragraph('<b>8.1 Primary Swarm (Critical)</b>', heading2))

primary_data = [
    [Paragraph('<b>Model</b>', table_header), Paragraph('<b>Registry ID</b>', table_header), Paragraph('<b>Role</b>', table_header)],
    [Paragraph('orchestrator', table_cell), Paragraph('baronki1/orchestrator', table_cell), Paragraph('System coordination, 75-module management', table_cell)],
    [Paragraph('security', table_cell), Paragraph('baronki1/security', table_cell), Paragraph('HexStrike Guard, 150+ security tools', table_cell)],
    [Paragraph('ciec', table_cell), Paragraph('baronki1/ciec', table_cell), Paragraph('Industrial AI, PLC/SCADA integration', table_cell)],
    [Paragraph('tcs', table_cell), Paragraph('baronki1/tcs', table_cell), Paragraph('Solar energy, zero-emission compute', table_cell)],
    [Paragraph('knowledge', table_cell), Paragraph('baronki1/knowledge', table_cell), Paragraph('RAG operations, knowledge graph', table_cell)],
    [Paragraph('installer', table_cell), Paragraph('baronki1/installer', table_cell), Paragraph('Autonomous deployment, error recovery', table_cell)],
]

primary_table = Table(primary_data, colWidths=[3*cm, 5*cm, 6*cm])
primary_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
    ('TEXTCOLOR', (0, 0), (-1, 0), HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), ROW_ODD),
    ('BACKGROUND', (0, 5), (-1, 5), ROW_EVEN),
    ('BACKGROUND', (0, 6), (-1, 6), ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(Spacer(1, 0.5*cm))
story.append(primary_table)

story.append(Spacer(1, 0.5*cm))
pull_text = """
<b>Quick Pull Command:</b> for model in orchestrator security ciec tcs knowledge installer; do ollama pull baronki1/$model; done
"""
story.append(Paragraph(pull_text.strip(), body_style))

# Build PDF
doc.build(story)
print(f"PDF generated: {output_path}")
