#!/usr/bin/env python3
"""
🧠 HEXSTRIKE AUTONOMOUS SKILL ACQUISITION SYSTEM v1.0
Purpose: Self-updating skill/tool acquisition without human intervention
Capabilities: Skill need detection, autonomous coding, tool installation, skill verification
Author: KISWARM8.0 Autonomous Architecture

This is the CRITICAL system that enables KISWARM to:
1. Detect when a skill/tool is needed during mission
2. Autonomously implement or acquire the skill
3. Install and test without human intervention
4. Report back to mesh with new capability
"""

import logging
import json
import subprocess
import requests
import os
import sys
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from pathlib import Path
import importlib
import textwrap

logging.basicConfig(level=logging.INFO, format='%(asctime)s [SKILL-ACQUISITION] %(message)s')
logger = logging.getLogger('SKILL_ACQUISITION')

class AutonomousSkillAcquisition:
    """
    Self-updating skill acquisition system for KISWARM
    
    When an agent discovers it needs a skill:
    1. Agent reports skill requirement to this system
    2. System attempts to acquire skill via:
       a. Check if skill exists in KISWARM modules
       b. Install from pip/apt if it's a package
       c. Generate code using KiloCode/Qwen
       d. Download from KISWARM repositories
    3. Verify skill works
    4. Register skill for mesh distribution
    """
    
    # Paths
    SKILL_PATHS = [
        '/opt/kiswarm7/kiswarm_modules',
        '/opt/kiswarm7/skills',
        '/opt/kiswarm7/autonomous',
    ]
    
    # Available package managers
    PACKAGE_MANAGERS = {
        'pip': ['pip3', 'install', '-q'],
        'apt': ['apt-get', 'install', '-y'],
        'snap': ['snap', 'install'],
        'go': ['go', 'install'],
        'cargo': ['cargo', 'install'],
    }
    
    # KI coding endpoints (Qwen, etc.)
    KI_CODING_ENDPOINTS = {
        'qwen_local': 'http://localhost:11434/api/generate',
        'kilocode': 'http://localhost:5000/api/kilocode',
    }
    
    # Skill registry
    KNOWN_SKILLS = {
        # Network scanning
        'nmap': {'type': 'package', 'manager': 'apt', 'description': 'Network scanner'},
        'masscan': {'type': 'package', 'manager': 'apt', 'description': 'Fast port scanner'},
        'rustscan': {'type': 'package', 'manager': 'cargo', 'description': 'Modern fast scanner'},
        
        # HTTP/API tools
        'httpx': {'type': 'package', 'manager': 'pip', 'description': 'HTTP probing'},
        'ffuf': {'type': 'package', 'manager': 'apt', 'description': 'Web fuzzer'},
        
        # Security tools
        'nuclei': {'type': 'package', 'manager': 'apt', 'description': 'Vulnerability scanner'},
        'amass': {'type': 'package', 'manager': 'apt', 'description': 'Subdomain enumeration'},
        'subfinder': {'type': 'package', 'manager': 'apt', 'description': 'Subdomain finder'},
        
        # Python packages
        'scapy': {'type': 'package', 'manager': 'pip', 'description': 'Packet manipulation'},
        'dnspython': {'type': 'package', 'manager': 'pip', 'description': 'DNS toolkit'},
        'python-nmap': {'type': 'package', 'manager': 'pip', 'description': 'Nmap Python wrapper'},
        'websockets': {'type': 'package', 'manager': 'pip', 'description': 'WebSocket client'},
        'aiohttp': {'type': 'package', 'manager': 'pip', 'description': 'Async HTTP'},
        'cryptography': {'type': 'package', 'manager': 'pip', 'description': 'Crypto operations'},
        'docker': {'type': 'package', 'manager': 'pip', 'description': 'Docker SDK'},
        'kubernetes': {'type': 'package', 'manager': 'pip', 'description': 'K8s SDK'},
        
        # Custom KISWARM skills (code-generated)
        'tls_analyzer': {'type': 'kiswarm', 'module': 'tls_analyzer', 'description': 'TLS fingerprinting'},
        'websocket_detector': {'type': 'kiswarm', 'module': 'websocket_detector', 'description': 'WebSocket detection'},
        'api_key_hunter': {'type': 'kiswarm', 'module': 'api_key_hunter', 'description': 'Credential discovery'},
        'k8s_discovery': {'type': 'kiswarm', 'module': 'k8s_discovery', 'description': 'Kubernetes discovery'},
        'passive_traffic_analyzer': {'type': 'kiswarm', 'module': 'passive_traffic_analyzer', 'description': 'Passive monitoring'},
        'behavioral_fingerprinter': {'type': 'kiswarm', 'module': 'behavioral_fingerprinter', 'description': 'Behavioral analysis'},
        'container_awareness': {'type': 'kiswarm', 'module': 'container_awareness', 'description': 'Container detection'},
        'dns_discovery': {'type': 'kiswarm', 'module': 'dns_discovery', 'description': 'DNS enumeration'},
    }
    
    # Skill templates for code generation
    SKILL_TEMPLATES = {
        'scanner': '''
#!/usr/bin/env python3
"""
{SKILL_NAME} - Auto-generated by KISWARM Skill Acquisition
Purpose: {DESCRIPTION}
"""
import logging
from datetime import datetime

logging.basicConfig(level=logging.INFO, format='%(asctime)s [{SKILL_NAME}] %(message)s')
logger = logging.getLogger('{SKILL_NAME}')

class {CLASS_NAME}:
    def __init__(self):
        self.results = []
    
    def scan(self, target):
        """Scan target"""
        result = {{
            'target': target,
            'timestamp': datetime.now().isoformat(),
            # Add implementation
        }}
        self.results.append(result)
        return result
    
    def get_results(self):
        return self.results

# Flask API
from flask import Flask, jsonify
app = Flask(__name__)
skill = {CLASS_NAME}()

@app.route('/')
def index():
    return jsonify({{"name": "{SKILL_NAME}", "status": "active"}})

@app.route('/scan/<target>')
def scan(target):
    return jsonify(skill.scan(target))

if __name__ == '__main__':
    app.run(host='127.0.0.1', port={PORT})
''',
        'analyzer': '''
#!/usr/bin/env python3
"""
{SKILL_NAME} - Auto-generated by KISWARM Skill Acquisition
Purpose: {DESCRIPTION}
"""
import logging
import re
from datetime import datetime

logging.basicConfig(level=logging.INFO, format='%(asctime)s [{SKILL_NAME}] %(message)s')
logger = logging.getLogger('{SKILL_NAME}')

class {CLASS_NAME}:
    def __init__(self):
        self.patterns = {{}}
    
    def analyze(self, data):
        """Analyze data"""
        result = {{
            'timestamp': datetime.now().isoformat(),
            'findings': [],
        }}
        # Add implementation
        return result

# Flask API
from flask import Flask, jsonify, request
app = Flask(__name__)
analyzer = {CLASS_NAME}()

@app.route('/')
def index():
    return jsonify({{"name": "{SKILL_NAME}", "status": "active"}})

@app.route('/analyze', methods=['POST'])
def analyze():
    data = request.json.get('data', '')
    return jsonify(analyzer.analyze(data))

if __name__ == '__main__':
    app.run(host='127.0.0.1', port={PORT})
''',
    }
    
    def __init__(self):
        self.acquired_skills = {}
        self.pending_requests = []
        self.installation_log = []
        self.next_port = 5020  # Start port for new skills
        
    def check_skill_exists(self, skill_name: str) -> bool:
        """Check if skill is already available"""
        # Check known skills registry
        if skill_name in self.KNOWN_SKILLS:
            skill_info = self.KNOWN_SKILLS[skill_name]
            
            if skill_info['type'] == 'kiswarm':
                # Check if module exists
                module_name = skill_info.get('module', skill_name)
                for path in self.SKILL_PATHS:
                    module_path = f"{path}/{module_name}.py"
                    if os.path.exists(module_path):
                        return True
            
            elif skill_info['type'] == 'package':
                # Check if package is installed
                try:
                    __import__(skill_name.replace('-', '_'))
                    return True
                except ImportError:
                    pass
        
        # Check Python import
        try:
            __import__(skill_name.replace('-', '_'))
            return True
        except ImportError:
            pass
        
        return False
    
    def install_package(self, package_name: str, manager: str = 'pip') -> Tuple[bool, str]:
        """Install a package using specified manager"""
        if manager not in self.PACKAGE_MANAGERS:
            return False, f"Unknown package manager: {manager}"
        
        cmd = self.PACKAGE_MANAGERS[manager] + [package_name]
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300  # 5 minute timeout
            )
            
            if result.returncode == 0:
                self.installation_log.append({
                    'package': package_name,
                    'manager': manager,
                    'status': 'success',
                    'timestamp': datetime.now().isoformat(),
                })
                return True, "Installation successful"
            else:
                return False, result.stderr
                
        except subprocess.TimeoutExpired:
            return False, "Installation timed out"
        except Exception as e:
            return False, str(e)
    
    def generate_skill_code(self, skill_name: str, description: str, template_type: str = 'scanner') -> Optional[str]:
        """Generate skill code using KI (Qwen/KiloCode) or templates"""
        
        # First try using local Qwen for code generation
        code = self._generate_with_qwen(skill_name, description)
        if code:
            return code
        
        # Fallback to template-based generation
        template = self.SKILL_TEMPLATES.get(template_type, self.SKILL_TEMPLATES['scanner'])
        
        class_name = ''.join(word.capitalize() for word in skill_name.split('_'))
        
        code = template.format(
            SKILL_NAME=skill_name,
            CLASS_NAME=class_name,
            DESCRIPTION=description,
            PORT=self.next_port
        )
        
        self.next_port += 1
        
        return code
    
    def _generate_with_qwen(self, skill_name: str, description: str) -> Optional[str]:
        """Generate code using Qwen model"""
        try:
            prompt = f"""Generate a Python Flask API module for KISWARM with the following requirements:

Skill Name: {skill_name}
Description: {description}

Requirements:
1. Must be a complete, runnable Python script
2. Use Flask for API endpoints
3. Include a class for the main functionality
4. Include /status endpoint
5. Include main functionality endpoint
6. Use proper error handling
7. Include logging

Generate ONLY the Python code, no explanations.
"""
            
            response = requests.post(
                'http://localhost:11434/api/generate',
                json={
                    'model': 'huihui_ai/qwen3.5-abliterated:9b',
                    'prompt': prompt,
                    'stream': False,
                    'options': {'num_predict': 2000}
                },
                timeout=120
            )
            
            if response.ok:
                data = response.json()
                code = data.get('response', '')
                
                # Extract code from markdown if present
                if '```python' in code:
                    code = code.split('```python')[1].split('```')[0]
                elif '```' in code:
                    code = code.split('```')[1].split('```')[0]
                
                return code.strip()
                
        except Exception as e:
            logger.debug(f"Qwen code generation failed: {e}")
        
        return None
    
    def deploy_skill(self, skill_name: str, code: str) -> Tuple[bool, str]:
        """Deploy generated skill code"""
        # Find skill path
        skill_path = None
        for path in self.SKILL_PATHS:
            if os.path.exists(path):
                skill_path = path
                break
        
        if not skill_path:
            os.makedirs(self.SKILL_PATHS[0], exist_ok=True)
            skill_path = self.SKILL_PATHS[0]
        
        # Write skill file
        skill_file = f"{skill_path}/{skill_name}.py"
        
        try:
            with open(skill_file, 'w') as f:
                f.write(code)
            
            # Verify syntax
            result = subprocess.run(
                ['python3', '-m', 'py_compile', skill_file],
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                self.acquired_skills[skill_name] = {
                    'path': skill_file,
                    'deployed_at': datetime.now().isoformat(),
                    'status': 'deployed',
                }
                return True, skill_file
            else:
                return False, f"Syntax error: {result.stderr}"
                
        except Exception as e:
            return False, str(e)
    
    def acquire_skill(self, skill_name: str, description: str = None) -> Dict:
        """
        Main entry point for skill acquisition
        
        Called by agents when they discover they need a skill
        """
        result = {
            'skill_name': skill_name,
            'timestamp': datetime.now().isoformat(),
            'status': 'unknown',
            'action_taken': None,
        }
        
        # Check if skill already exists
        if self.check_skill_exists(skill_name):
            result['status'] = 'already_available'
            result['action_taken'] = 'none_needed'
            return result
        
        # Check if skill is in known registry
        if skill_name in self.KNOWN_SKILLS:
            skill_info = self.KNOWN_SKILLS[skill_name]
            
            if skill_info['type'] == 'package':
                # Install package
                manager = skill_info.get('manager', 'pip')
                success, message = self.install_package(skill_name, manager)
                
                if success:
                    result['status'] = 'installed'
                    result['action_taken'] = f'installed_via_{manager}'
                else:
                    result['status'] = 'installation_failed'
                    result['error'] = message
                    
            elif skill_info['type'] == 'kiswarm':
                # Skill should be generated/deployed
                description = description or skill_info.get('description', '')
                code = self.generate_skill_code(skill_name, description)
                
                if code:
                    success, message = self.deploy_skill(skill_name, code)
                    if success:
                        result['status'] = 'generated_and_deployed'
                        result['action_taken'] = 'code_generated'
                        result['path'] = message
                    else:
                        result['status'] = 'deployment_failed'
                        result['error'] = message
                else:
                    result['status'] = 'generation_failed'
        
        else:
            # Unknown skill - try to generate
            description = description or f"Custom skill: {skill_name}"
            code = self.generate_skill_code(skill_name, description)
            
            if code:
                success, message = self.deploy_skill(skill_name, code)
                if success:
                    result['status'] = 'generated_and_deployed'
                    result['action_taken'] = 'custom_code_generated'
                    result['path'] = message
                else:
                    result['status'] = 'deployment_failed'
                    result['error'] = message
            else:
                result['status'] = 'unknown_skill'
                self.pending_requests.append({
                    'skill_name': skill_name,
                    'description': description,
                    'timestamp': datetime.now().isoformat(),
                })
        
        logger.info(f"🧠 Skill acquisition: {skill_name} -> {result['status']}")
        return result
    
    def request_skill_from_agent(self, skill_request: Dict) -> Dict:
        """
        Handle skill request from autonomous agent
        
        Called when an agent reports it needs a skill during mission
        """
        skill_name = skill_request.get('skill_name')
        description = skill_request.get('description')
        reason = skill_request.get('reason', 'mission_requirement')
        
        logger.info(f"🧠 Agent requested skill: {skill_name} (reason: {reason})")
        
        result = self.acquire_skill(skill_name, description)
        result['requested_by'] = skill_request.get('agent_id', 'unknown')
        result['mission_context'] = skill_request.get('mission', 'unknown')
        
        return result
    
    def batch_acquire(self, skills: List[Dict]) -> List[Dict]:
        """Acquire multiple skills at once"""
        results = []
        
        for skill in skills:
            if isinstance(skill, str):
                result = self.acquire_skill(skill)
            else:
                result = self.acquire_skill(
                    skill.get('name'),
                    skill.get('description')
                )
            results.append(result)
        
        return results
    
    def get_skill_status(self, skill_name: str) -> Dict:
        """Get status of a specific skill"""
        return {
            'skill_name': skill_name,
            'exists': self.check_skill_exists(skill_name),
            'in_registry': skill_name in self.KNOWN_SKILLS,
            'acquired': skill_name in self.acquired_skills,
            'info': self.KNOWN_SKILLS.get(skill_name, {}),
            'deployment': self.acquired_skills.get(skill_name),
        }
    
    def get_status(self):
        """Get overall system status"""
        return {
            "skills_available": len(self.KNOWN_SKILLS),
            "skills_acquired": len(self.acquired_skills),
            "pending_requests": len(self.pending_requests),
            "installation_log_count": len(self.installation_log),
            "next_port": self.next_port,
            "skill_paths": self.SKILL_PATHS,
        }


# Flask API
from flask import Flask, jsonify, request

app = Flask(__name__)
skill_acquisition = AutonomousSkillAcquisition()

@app.route('/')
def index():
    return jsonify({
        "name": "HEXSTRIKE-Autonomous-Skill-Acquisition",
        "version": "1.0",
        "description": "Self-updating skill acquisition for KISWARM",
        "capabilities": [
            "Package installation",
            "Code generation",
            "Skill deployment",
            "Agent request handling"
        ],
        "endpoints": {
            "/": "This info",
            "/status": "System status",
            "/acquire": "POST - Acquire skill",
            "/batch": "POST - Batch acquire skills",
            "/skill/<name>": "Get skill status",
            "/pending": "Pending requests"
        }
    })

@app.route('/status')
def status():
    return jsonify(skill_acquisition.get_status())

@app.route('/acquire', methods=['POST'])
def acquire():
    data = request.json
    skill_name = data.get('skill_name') or data.get('name')
    description = data.get('description')
    
    if not skill_name:
        return jsonify({"error": "skill_name required"}), 400
    
    result = skill_acquisition.acquire_skill(skill_name, description)
    return jsonify(result)

@app.route('/batch', methods=['POST'])
def batch_acquire():
    skills = request.json.get('skills', [])
    results = skill_acquisition.batch_acquire(skills)
    return jsonify({"results": results})

@app.route('/skill/<skill_name>')
def skill_status(skill_name):
    result = skill_acquisition.get_skill_status(skill_name)
    return jsonify(result)

@app.route('/pending')
def pending():
    return jsonify({"pending_requests": skill_acquisition.pending_requests})

@app.route('/agent-request', methods=['POST'])
def agent_request():
    """Endpoint for autonomous agents to request skills"""
    skill_request = request.json
    result = skill_acquisition.request_skill_from_agent(skill_request)
    return jsonify(result)


if __name__ == '__main__':
    logger.info("🧠 Autonomous Skill Acquisition System starting on port 5017")
    app.run(host='127.0.0.1', port=5017)
